### ISSUE TITLE
Thank you for sharing this repository! It really cleared up a lot of things about integrating Ory Kratos into Nuxt =) ❤️❤️❤️

### ISSUE THREAD

**Issue by aidar31** [khusseini/nuxt-kratos-selfservice#1]
Thanks!!❤️❤️❤️

**Comment by khusseini** [comment]
You're most welcome. Over time I found some issues in the code I shared but I didn't get around to fixing them, the API to Kratos communication is wonky and the separation of FE and BE are not clean. In my actual project I ended up securing the API with Oathkeeper to make the separation easier.

**Comment by aidar31** [comment]
Thanks for sharing. 
Now I'm still thinking about using Oathkeeper.

**Comment by aidar31** [comment]
How did you use OathKeeper? I noticed that it is also used for securing self-service in the ory/kratos repo, which seemed a bit strange to me because I thought it was meant purely for API security.
